version: '3.9'
services:
  api:
    build: .
    container_name: mj-api
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    container_name: mj-redis
    restart: always

  puppeteer:
    build:
      context: ./puppeteer
    container_name: mj-puppeteer
    env_file: .env
    restart: always
